// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accommodations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccommodation = `-- name: CreateAccommodation :one
INSERT INTO accommodations (trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at
`

type CreateAccommodationParams struct {
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	Address   *string     `json:"address"`
	Latitude  *float64    `json:"latitude"`
	Longitude *float64    `json:"longitude"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
}

func (q *Queries) CreateAccommodation(ctx context.Context, arg CreateAccommodationParams) (Accommodation, error) {
	row := q.db.QueryRow(ctx, createAccommodation,
		arg.TripID,
		arg.Name,
		arg.Provider,
		arg.Url,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CheckIn,
		arg.CheckOut,
		arg.PriceNote,
	)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CheckIn,
		&i.CheckOut,
		&i.PriceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccommodation = `-- name: DeleteAccommodation :execrows
DELETE FROM accommodations WHERE id = $1 AND trip_id = $2
`

type DeleteAccommodationParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteAccommodation(ctx context.Context, arg DeleteAccommodationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccommodation, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccommodationsByTrip = `-- name: ListAccommodationsByTrip :many
SELECT id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at FROM accommodations WHERE trip_id = $1 ORDER BY check_in ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListAccommodationsByTrip(ctx context.Context, tripID uuid.UUID) ([]Accommodation, error) {
	rows, err := q.db.Query(ctx, listAccommodationsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Provider,
			&i.Url,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CheckIn,
			&i.CheckOut,
			&i.PriceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
