// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminTotals = `-- name: AdminTotals :one
SELECT
  (SELECT count(*) FROM users)::bigint AS users,
  (SELECT count(*) FROM users WHERE email_verified_at IS NOT NULL)::bigint AS verified_users,
  (SELECT count(*) FROM users WHERE onboarded_at IS NOT NULL)::bigint AS onboarded_users,
  (SELECT count(*) FROM trips)::bigint AS trips,
  -- Lineages: COALESCE(chat_id, id) — the My Trips grouping, same rule as
  -- UserEngagementCounts in analytics.sql.
  (SELECT count(DISTINCT COALESCE(chat_id, id::text)) FROM trips)::bigint AS trip_lineages,
  (SELECT count(*) FROM itinerary_items)::bigint AS itinerary_items,
  (SELECT count(*) FROM booking_todos)::bigint AS booking_todos,
  (SELECT count(*) FROM price_alerts WHERE status = 'active')::bigint AS active_price_alerts,
  (SELECT count(*) FROM local_recommendations WHERE status = 'published')::bigint AS published_local_recs,
  (SELECT count(*) FROM local_guides)::bigint AS local_guides,
  (SELECT count(*) FROM trip_collaborators WHERE revoked_at IS NULL)::bigint AS active_collaborators,
  (SELECT count(*) FROM trip_shares WHERE revoked_at IS NULL)::bigint AS active_shares,
  (SELECT count(*) FROM sessions WHERE expires_at > now())::bigint AS active_sessions,
  (SELECT count(*) FROM analytics_events)::bigint AS analytics_events
`

type AdminTotalsRow struct {
	Users               int64 `json:"users"`
	VerifiedUsers       int64 `json:"verified_users"`
	OnboardedUsers      int64 `json:"onboarded_users"`
	Trips               int64 `json:"trips"`
	TripLineages        int64 `json:"trip_lineages"`
	ItineraryItems      int64 `json:"itinerary_items"`
	BookingTodos        int64 `json:"booking_todos"`
	ActivePriceAlerts   int64 `json:"active_price_alerts"`
	PublishedLocalRecs  int64 `json:"published_local_recs"`
	LocalGuides         int64 `json:"local_guides"`
	ActiveCollaborators int64 `json:"active_collaborators"`
	ActiveShares        int64 `json:"active_shares"`
	ActiveSessions      int64 `json:"active_sessions"`
	AnalyticsEvents     int64 `json:"analytics_events"`
}

// All-time live counts straight off the domain tables — the numbers the
// event-log rollups in analytics.sql cannot produce (events only exist since
// 00026, and deletes never reach the log). One round trip of scalar
// subselects; each is an index or small-table scan at current scale.
func (q *Queries) AdminTotals(ctx context.Context) (AdminTotalsRow, error) {
	row := q.db.QueryRow(ctx, adminTotals)
	var i AdminTotalsRow
	err := row.Scan(
		&i.Users,
		&i.VerifiedUsers,
		&i.OnboardedUsers,
		&i.Trips,
		&i.TripLineages,
		&i.ItineraryItems,
		&i.BookingTodos,
		&i.ActivePriceAlerts,
		&i.PublishedLocalRecs,
		&i.LocalGuides,
		&i.ActiveCollaborators,
		&i.ActiveShares,
		&i.ActiveSessions,
		&i.AnalyticsEvents,
	)
	return i, err
}

const adminUserActivity = `-- name: AdminUserActivity :many
SELECT u.id, u.email, u.display_name, u.is_admin,
       u.created_at AS signed_up_at,
       (u.onboarded_at IS NOT NULL)::boolean AS onboarded,
       (u.email_verified_at IS NOT NULL)::boolean AS email_verified,
       COALESCE(t.trips, 0)::bigint AS trips,
       COALESCE(t.trip_lineages, 0)::bigint AS trip_lineages,
       COALESCE(a.plan_sessions, 0)::bigint AS plan_sessions,
       COALESCE(a.booking_clicks, 0)::bigint AS booking_clicks,
       COALESCE(a.input_tokens, 0)::bigint AS plan_input_tokens,
       COALESCE(a.output_tokens, 0)::bigint AS plan_output_tokens,
       COALESCE(a.cache_read_tokens, 0)::bigint AS plan_cache_read_tokens,
       COALESCE(a.cache_creation_tokens, 0)::bigint AS plan_cache_creation_tokens,
       a.last_event_at
FROM users u
LEFT JOIN (
  SELECT user_id, count(*) AS trips,
         count(DISTINCT COALESCE(chat_id, id::text)) AS trip_lineages
  FROM trips GROUP BY user_id
) t ON t.user_id = u.id
LEFT JOIN (
  SELECT user_id,
         count(*) FILTER (WHERE event_type = 'plan_session_started') AS plan_sessions,
         count(*) FILTER (WHERE event_type = 'booking_link_clicked') AS booking_clicks,
         sum((metadata->>'input_tokens')::bigint) FILTER (WHERE event_type = 'plan_session_completed') AS input_tokens,
         sum((metadata->>'output_tokens')::bigint) FILTER (WHERE event_type = 'plan_session_completed') AS output_tokens,
         sum((metadata->>'cache_read_tokens')::bigint) FILTER (WHERE event_type = 'plan_session_completed') AS cache_read_tokens,
         sum((metadata->>'cache_creation_tokens')::bigint) FILTER (WHERE event_type = 'plan_session_completed') AS cache_creation_tokens,
         max(created_at) AS last_event_at
  FROM analytics_events
  WHERE user_id IS NOT NULL
  GROUP BY user_id
) a ON a.user_id = u.id
ORDER BY a.last_event_at DESC NULLS LAST, u.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminUserActivityParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminUserActivityRow struct {
	ID                      uuid.UUID   `json:"id"`
	Email                   string      `json:"email"`
	DisplayName             *string     `json:"display_name"`
	IsAdmin                 bool        `json:"is_admin"`
	SignedUpAt              time.Time   `json:"signed_up_at"`
	Onboarded               bool        `json:"onboarded"`
	EmailVerified           bool        `json:"email_verified"`
	Trips                   int64       `json:"trips"`
	TripLineages            int64       `json:"trip_lineages"`
	PlanSessions            int64       `json:"plan_sessions"`
	BookingClicks           int64       `json:"booking_clicks"`
	PlanInputTokens         int64       `json:"plan_input_tokens"`
	PlanOutputTokens        int64       `json:"plan_output_tokens"`
	PlanCacheReadTokens     int64       `json:"plan_cache_read_tokens"`
	PlanCacheCreationTokens int64       `json:"plan_cache_creation_tokens"`
	LastEventAt             interface{} `json:"last_event_at"`
}

// Per-user drill-down rows: users LEFT JOIN two grouped subqueries (trips by
// lineage, and analytics rollups). Token sums are FILTERed to
// plan_session_completed — the same guard as PlanSessionTotals — so no other
// event's metadata is ever summed; (metadata->>'k')::bigint is NULL when the
// key is absent and sum() skips NULLs.
func (q *Queries) AdminUserActivity(ctx context.Context, arg AdminUserActivityParams) ([]AdminUserActivityRow, error) {
	rows, err := q.db.Query(ctx, adminUserActivity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminUserActivityRow
	for rows.Next() {
		var i AdminUserActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.IsAdmin,
			&i.SignedUpAt,
			&i.Onboarded,
			&i.EmailVerified,
			&i.Trips,
			&i.TripLineages,
			&i.PlanSessions,
			&i.BookingClicks,
			&i.PlanInputTokens,
			&i.PlanOutputTokens,
			&i.PlanCacheReadTokens,
			&i.PlanCacheCreationTokens,
			&i.LastEventAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const eventDailyCounts = `-- name: EventDailyCounts :many

SELECT (created_at AT TIME ZONE 'UTC')::date AS day,
       event_type,
       count(*)::bigint AS n
FROM analytics_events
WHERE created_at >= $1 AND event_type = ANY($2::text[])
GROUP BY 1, 2
ORDER BY 1
`

type EventDailyCountsParams struct {
	Since      time.Time `json:"since"`
	EventTypes []string  `json:"event_types"`
}

type EventDailyCountsRow struct {
	Day       pgtype.Date `json:"day"`
	EventType string      `json:"event_type"`
	N         int64       `json:"n"`
}

// Admin analytics dashboard extensions (trends / totals / activity / users).
// Read-only rollups behind /api/v1/admin/metrics/*; nothing here is written to.
// Daily buckets for the Trends tab. Bucketing is explicit UTC so results do
// not depend on the server's TimeZone GUC. Output is sparse — days with zero
// events are absent; the client fills gaps (it knows start_day and days, so
// shipping generate_series zeros would only bloat the payload).
func (q *Queries) EventDailyCounts(ctx context.Context, arg EventDailyCountsParams) ([]EventDailyCountsRow, error) {
	rows, err := q.db.Query(ctx, eventDailyCounts, arg.Since, arg.EventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventDailyCountsRow
	for rows.Next() {
		var i EventDailyCountsRow
		if err := rows.Scan(&i.Day, &i.EventType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAnalyticsEvents = `-- name: RecentAnalyticsEvents :many
SELECT e.id, e.event_type, e.user_id,
       COALESCE(u.email, '')::text AS user_email,
       COALESCE(u.is_admin, false)::boolean AS user_is_admin,
       e.trip_id, e.metadata, e.created_at
FROM analytics_events e
LEFT JOIN users u ON u.id = e.user_id
WHERE e.created_at < $1
  AND (NOT $2::bool OR NOT COALESCE(u.is_admin, false))
ORDER BY e.created_at DESC
LIMIT $3
`

type RecentAnalyticsEventsParams struct {
	Before        time.Time `json:"before"`
	ExcludeAdmins bool      `json:"exclude_admins"`
	PageLimit     int32     `json:"page_limit"`
}

type RecentAnalyticsEventsRow struct {
	ID          uuid.UUID   `json:"id"`
	EventType   string      `json:"event_type"`
	UserID      pgtype.UUID `json:"user_id"`
	UserEmail   string      `json:"user_email"`
	UserIsAdmin bool        `json:"user_is_admin"`
	TripID      pgtype.UUID `json:"trip_id"`
	Metadata    []byte      `json:"metadata"`
	CreatedAt   time.Time   `json:"created_at"`
}

// Activity-feed tail, keyset-paginated: the client passes the last row's
// created_at back as $1 for the next page. COALESCE keeps sqlc's LEFT-JOIN
// nullability simple; the handler decides "anonymous" from user_id being
// NULL, never from an empty email. When exclude_admins is true, rows from
// admin users are dropped so the operator's own clicks don't pollute the
// funnel/activity feed (anonymous rows survive — NULL is_admin COALESCEs to
// false). ORDER BY created_at DESC is served by the bare created_at index
// added in 00043.
func (q *Queries) RecentAnalyticsEvents(ctx context.Context, arg RecentAnalyticsEventsParams) ([]RecentAnalyticsEventsRow, error) {
	rows, err := q.db.Query(ctx, recentAnalyticsEvents, arg.Before, arg.ExcludeAdmins, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAnalyticsEventsRow
	for rows.Next() {
		var i RecentAnalyticsEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.UserID,
			&i.UserEmail,
			&i.UserIsAdmin,
			&i.TripID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
