// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadAlertEvents = `-- name: CountUnreadAlertEvents :one
SELECT count(*) FROM alert_events
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadAlertEvents(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAlertEvents, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO alert_events (alert_id, user_id, price, currency, previous_price, matched_departure_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, alert_id, user_id, price, currency, previous_price, occurred_at, read_at, matched_departure_date
`

type InsertAlertEventParams struct {
	AlertID              uuid.UUID   `json:"alert_id"`
	UserID               uuid.UUID   `json:"user_id"`
	Price                float64     `json:"price"`
	Currency             string      `json:"currency"`
	PreviousPrice        *float64    `json:"previous_price"`
	MatchedDepartureDate pgtype.Date `json:"matched_departure_date"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent,
		arg.AlertID,
		arg.UserID,
		arg.Price,
		arg.Currency,
		arg.PreviousPrice,
		arg.MatchedDepartureDate,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.UserID,
		&i.Price,
		&i.Currency,
		&i.PreviousPrice,
		&i.OccurredAt,
		&i.ReadAt,
		&i.MatchedDepartureDate,
	)
	return i, err
}

const listAlertEventsByUser = `-- name: ListAlertEventsByUser :many
SELECT alert_events.id, alert_events.alert_id, alert_events.price,
       alert_events.currency, alert_events.previous_price,
       alert_events.matched_departure_date,
       alert_events.occurred_at, alert_events.read_at,
       price_alerts.origin, price_alerts.destination,
       price_alerts.depart_date, price_alerts.return_date,
       price_alerts.target_price, price_alerts.status AS alert_status
FROM alert_events
JOIN price_alerts ON price_alerts.id = alert_events.alert_id
WHERE alert_events.user_id = $1
ORDER BY alert_events.occurred_at DESC, alert_events.id DESC
LIMIT $2
`

type ListAlertEventsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListAlertEventsByUserRow struct {
	ID                   uuid.UUID          `json:"id"`
	AlertID              uuid.UUID          `json:"alert_id"`
	Price                float64            `json:"price"`
	Currency             string             `json:"currency"`
	PreviousPrice        *float64           `json:"previous_price"`
	MatchedDepartureDate pgtype.Date        `json:"matched_departure_date"`
	OccurredAt           time.Time          `json:"occurred_at"`
	ReadAt               pgtype.Timestamptz `json:"read_at"`
	Origin               string             `json:"origin"`
	Destination          string             `json:"destination"`
	DepartDate           pgtype.Date        `json:"depart_date"`
	ReturnDate           pgtype.Date        `json:"return_date"`
	TargetPrice          *float64           `json:"target_price"`
	AlertStatus          string             `json:"alert_status"`
}

// The joined alert columns give the client the route/dates context inline so
// rendering a notification never needs a second request. The join is inner on
// purpose: deleting an alert cascades its events away.
func (q *Queries) ListAlertEventsByUser(ctx context.Context, arg ListAlertEventsByUserParams) ([]ListAlertEventsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertEventsByUserRow
	for rows.Next() {
		var i ListAlertEventsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Price,
			&i.Currency,
			&i.PreviousPrice,
			&i.MatchedDepartureDate,
			&i.OccurredAt,
			&i.ReadAt,
			&i.Origin,
			&i.Destination,
			&i.DepartDate,
			&i.ReturnDate,
			&i.TargetPrice,
			&i.AlertStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertEventsRead = `-- name: MarkAlertEventsRead :execrows
UPDATE alert_events
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

// Mark-all is the v1 read model (specs/price-alerts-v2): opening the
// notification center clears the badge wholesale. No per-event variant yet.
func (q *Queries) MarkAlertEventsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAlertEventsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
