// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookingClicksByProvider = `-- name: BookingClicksByProvider :many
SELECT COALESCE(metadata->>'provider', 'unknown')::text AS provider, count(*) AS clicks
FROM analytics_events
WHERE event_type = 'booking_link_clicked' AND created_at >= $1
GROUP BY 1 ORDER BY clicks DESC
`

type BookingClicksByProviderRow struct {
	Provider string `json:"provider"`
	Clicks   int64  `json:"clicks"`
}

func (q *Queries) BookingClicksByProvider(ctx context.Context, createdAt time.Time) ([]BookingClicksByProviderRow, error) {
	rows, err := q.db.Query(ctx, bookingClicksByProvider, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingClicksByProviderRow
	for rows.Next() {
		var i BookingClicksByProviderRow
		if err := rows.Scan(&i.Provider, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActivatedSignups = `-- name: CountActivatedSignups :one
SELECT count(DISTINCT r.user_id) FROM analytics_events r
JOIN analytics_events t ON t.user_id = r.user_id AND t.event_type = 'trip_created'
WHERE r.event_type = 'user_registered' AND r.created_at >= $1
`

// Users who registered in the window and have saved at least one trip (ever).
func (q *Queries) CountActivatedSignups(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countActivatedSignups, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAnonymousPlanSessions = `-- name: CountAnonymousPlanSessions :one
SELECT count(*) FROM analytics_events
WHERE event_type = 'plan_session_started' AND user_id IS NULL AND created_at >= $1
`

func (q *Queries) CountAnonymousPlanSessions(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAnonymousPlanSessions, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByType = `-- name: CountEventsByType :one
SELECT count(*) FROM analytics_events
WHERE event_type = $1 AND created_at >= $2
`

type CountEventsByTypeParams struct {
	EventType string    `json:"event_type"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByType, arg.EventType, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlanCapHits = `-- name: CountPlanCapHits :one
SELECT count(*) FROM analytics_events
WHERE event_type = 'plan_session_completed'
  AND (metadata->>'max_iterations_hit')::boolean
  AND created_at >= $1
`

// Sessions that hit the agent-loop iteration cap (free-tier pressure signal).
func (q *Queries) CountPlanCapHits(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countPlanCapHits, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReturningUsers = `-- name: CountReturningUsers :one
SELECT count(*) FROM (
  SELECT user_id FROM analytics_events
  WHERE event_type = 'plan_session_started' AND user_id IS NOT NULL AND created_at >= $1
  GROUP BY user_id
  HAVING count(DISTINCT date(created_at)) >= 2
) returning_users
`

// Users with planning sessions on at least two distinct days in the window.
// user_id IS NOT NULL: anonymous sessions must not group into a phantom user.
func (q *Queries) CountReturningUsers(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countReturningUsers, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTripsWithBookingClick = `-- name: CountTripsWithBookingClick :one
SELECT count(DISTINCT trip_id) FROM analytics_events
WHERE event_type = 'booking_link_clicked' AND trip_id IS NOT NULL AND created_at >= $1
`

func (q *Queries) CountTripsWithBookingClick(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsWithBookingClick, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalyticsEvent = `-- name: CreateAnalyticsEvent :exec
INSERT INTO analytics_events (user_id, event_type, trip_id, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateAnalyticsEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	TripID    pgtype.UUID `json:"trip_id"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAnalyticsEvent(ctx context.Context, arg CreateAnalyticsEventParams) error {
	_, err := q.db.Exec(ctx, createAnalyticsEvent,
		arg.UserID,
		arg.EventType,
		arg.TripID,
		arg.Metadata,
	)
	return err
}

const planSessionTotals = `-- name: PlanSessionTotals :one
SELECT count(*) AS sessions,
       COALESCE(sum((metadata->>'input_tokens')::bigint), 0)::bigint AS input_tokens,
       COALESCE(sum((metadata->>'output_tokens')::bigint), 0)::bigint AS output_tokens,
       COALESCE(sum((metadata->>'cache_read_tokens')::bigint), 0)::bigint AS cache_read_tokens,
       COALESCE(sum((metadata->>'cache_creation_tokens')::bigint), 0)::bigint AS cache_creation_tokens
FROM analytics_events
WHERE event_type = 'plan_session_completed' AND created_at >= $1
`

type PlanSessionTotalsRow struct {
	Sessions            int64 `json:"sessions"`
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	CacheReadTokens     int64 `json:"cache_read_tokens"`
	CacheCreationTokens int64 `json:"cache_creation_tokens"`
}

// Sessions + token spend from plan_session_completed metadata.
func (q *Queries) PlanSessionTotals(ctx context.Context, createdAt time.Time) (PlanSessionTotalsRow, error) {
	row := q.db.QueryRow(ctx, planSessionTotals, createdAt)
	var i PlanSessionTotalsRow
	err := row.Scan(
		&i.Sessions,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheCreationTokens,
	)
	return i, err
}
