// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookingClicksByProvider = `-- name: BookingClicksByProvider :many
SELECT COALESCE(left(metadata->>'provider', 64), 'unknown')::text AS provider, count(*) AS clicks
FROM analytics_events
WHERE event_type = 'booking_link_clicked' AND created_at >= $1
GROUP BY 1 ORDER BY clicks DESC, provider
LIMIT 20
`

type BookingClicksByProviderRow struct {
	Provider string `json:"provider"`
	Clicks   int64  `json:"clicks"`
}

// provider is client-supplied (sanitized at ingest since Wave 7, but older
// rows predate that): left(..., 64) + LIMIT 20 bound the admin dashboard's
// rollup against arbitrary historical values.
func (q *Queries) BookingClicksByProvider(ctx context.Context, createdAt time.Time) ([]BookingClicksByProviderRow, error) {
	rows, err := q.db.Query(ctx, bookingClicksByProvider, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingClicksByProviderRow
	for rows.Next() {
		var i BookingClicksByProviderRow
		if err := rows.Scan(&i.Provider, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActivatedSignups = `-- name: CountActivatedSignups :one
SELECT count(DISTINCT r.user_id) FROM analytics_events r
JOIN analytics_events t ON t.user_id = r.user_id AND t.event_type = 'trip_created'
WHERE r.event_type = 'user_registered' AND r.created_at >= $1
`

// Users who registered in the window and have saved at least one trip (ever).
func (q *Queries) CountActivatedSignups(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countActivatedSignups, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByTypeAndUserSince = `-- name: CountEventsByTypeAndUserSince :one
SELECT count(*) FROM analytics_events
WHERE event_type = $1 AND user_id = $2 AND created_at >= $3
`

type CountEventsByTypeAndUserSinceParams struct {
	EventType string      `json:"event_type"`
	UserID    pgtype.UUID `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
}

// Per-user event count for a trailing window — the free-cap crossing check
// (specs/free-cap-instrumentation). Counting off analytics_events undercounts
// in degraded mode; acceptable for a demand signal (see the spec).
func (q *Queries) CountEventsByTypeAndUserSince(ctx context.Context, arg CountEventsByTypeAndUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByTypeAndUserSince, arg.EventType, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByTypeGrouped = `-- name: CountEventsByTypeGrouped :many
SELECT event_type, count(*)::bigint AS n FROM analytics_events
WHERE created_at >= $1
GROUP BY event_type
`

type CountEventsByTypeGroupedRow struct {
	EventType string `json:"event_type"`
	N         int64  `json:"n"`
}

// All per-type counts for the metrics window in one round trip (the dashboard
// previously issued one CountEventsByType query per headline number).
func (q *Queries) CountEventsByTypeGrouped(ctx context.Context, createdAt time.Time) ([]CountEventsByTypeGroupedRow, error) {
	rows, err := q.db.Query(ctx, countEventsByTypeGrouped, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEventsByTypeGroupedRow
	for rows.Next() {
		var i CountEventsByTypeGroupedRow
		if err := rows.Scan(&i.EventType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTripsWithBookingClick = `-- name: CountTripsWithBookingClick :one
SELECT count(DISTINCT trip_id) FROM analytics_events
WHERE event_type = 'booking_link_clicked' AND trip_id IS NOT NULL AND created_at >= $1
`

func (q *Queries) CountTripsWithBookingClick(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countTripsWithBookingClick, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalyticsEvent = `-- name: CreateAnalyticsEvent :exec
INSERT INTO analytics_events (user_id, event_type, trip_id, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateAnalyticsEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	TripID    pgtype.UUID `json:"trip_id"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAnalyticsEvent(ctx context.Context, arg CreateAnalyticsEventParams) error {
	_, err := q.db.Exec(ctx, createAnalyticsEvent,
		arg.UserID,
		arg.EventType,
		arg.TripID,
		arg.Metadata,
	)
	return err
}

const freeCapWouldHitCounts = `-- name: FreeCapWouldHitCounts :many
SELECT COALESCE(metadata->>'cap_kind', 'unknown')::text AS cap_kind,
       count(*)::bigint AS would_hits,
       count(DISTINCT user_id)::bigint AS users_affected
FROM analytics_events
WHERE event_type = 'free_cap_would_hit' AND created_at >= $1
GROUP BY 1
`

type FreeCapWouldHitCountsRow struct {
	CapKind       string `json:"cap_kind"`
	WouldHits     int64  `json:"would_hits"`
	UsersAffected int64  `json:"users_affected"`
}

// Dashboard rollup for free_cap_would_hit: crossings observed plus the
// distinct users affected, per cap_kind (plan_runs / active_trips).
func (q *Queries) FreeCapWouldHitCounts(ctx context.Context, createdAt time.Time) ([]FreeCapWouldHitCountsRow, error) {
	rows, err := q.db.Query(ctx, freeCapWouldHitCounts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FreeCapWouldHitCountsRow
	for rows.Next() {
		var i FreeCapWouldHitCountsRow
		if err := rows.Scan(&i.CapKind, &i.WouldHits, &i.UsersAffected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planSessionTotals = `-- name: PlanSessionTotals :one
SELECT count(*) AS sessions,
       count(*) FILTER (WHERE user_id IS NULL)::bigint AS anonymous_sessions,
       count(*) FILTER (WHERE (metadata->>'max_iterations_hit')::boolean)::bigint AS agent_loop_cap_hits,
       COALESCE(sum((metadata->>'input_tokens')::bigint), 0)::bigint AS input_tokens,
       COALESCE(sum((metadata->>'output_tokens')::bigint), 0)::bigint AS output_tokens,
       COALESCE(sum((metadata->>'cache_read_tokens')::bigint), 0)::bigint AS cache_read_tokens,
       COALESCE(sum((metadata->>'cache_creation_tokens')::bigint), 0)::bigint AS cache_creation_tokens
FROM analytics_events
WHERE event_type = 'plan_session_completed' AND created_at >= $1
`

type PlanSessionTotalsRow struct {
	Sessions            int64 `json:"sessions"`
	AnonymousSessions   int64 `json:"anonymous_sessions"`
	AgentLoopCapHits    int64 `json:"agent_loop_cap_hits"`
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	CacheReadTokens     int64 `json:"cache_read_tokens"`
	CacheCreationTokens int64 `json:"cache_creation_tokens"`
}

// Sessions + token spend from plan_session_completed metadata, plus the
// anonymous split and agent-loop cap hits (all filters over the same
// completed-session denominator, folded into one round trip).
func (q *Queries) PlanSessionTotals(ctx context.Context, createdAt time.Time) (PlanSessionTotalsRow, error) {
	row := q.db.QueryRow(ctx, planSessionTotals, createdAt)
	var i PlanSessionTotalsRow
	err := row.Scan(
		&i.Sessions,
		&i.AnonymousSessions,
		&i.AgentLoopCapHits,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheCreationTokens,
	)
	return i, err
}

const userEngagementCounts = `-- name: UserEngagementCounts :one
SELECT
  (SELECT count(DISTINCT a.user_id) FROM analytics_events a
   WHERE a.event_type = 'plan_session_started' AND a.user_id IS NOT NULL
     AND a.created_at >= $1)::bigint AS active_users,
  (SELECT count(*) FROM (
     SELECT b.user_id FROM analytics_events b
     WHERE b.event_type = 'plan_session_started' AND b.user_id IS NOT NULL
       AND b.created_at >= $1
     GROUP BY b.user_id
     HAVING count(DISTINCT date(b.created_at)) >= 2
   ) s)::bigint AS session_frequency_returning,
  (SELECT count(*) FROM (
     SELECT l.user_id FROM (
       SELECT c.user_id, min(c.created_at) AS first_at
       FROM analytics_events c
       JOIN trips tr ON tr.id = c.trip_id
       WHERE c.event_type = 'trip_created' AND c.user_id IS NOT NULL
         AND c.created_at >= $1
       GROUP BY c.user_id, COALESCE(tr.chat_id, tr.id::text)
     ) l
     GROUP BY l.user_id
     HAVING max(l.first_at) - min(l.first_at) >= interval '7 days'
   ) t)::bigint AS second_trip_retention
`

type UserEngagementCountsRow struct {
	ActiveUsers               int64 `json:"active_users"`
	SessionFrequencyReturning int64 `json:"session_frequency_returning"`
	SecondTripRetention       int64 `json:"second_trip_retention"`
}

// The three user-level engagement numbers in one round trip.
// user_id IS NOT NULL everywhere: anonymous sessions must not group into a
// phantom user.
//
//	active_users               — MAU: distinct users who started >= 1 planning
//	                             session in the window.
//	session_frequency_returning — users with planning sessions on >= 2 distinct
//	                             days (a session-frequency proxy; NOT trip
//	                             retention).
//	second_trip_retention      — users whose trip_created events span >= 2
//	                             DISTINCT trip lineages (COALESCE(chat_id,
//	                             id) — the My Trips grouping) with first
//	                             creations >= 7 days apart (the business
//	                             model's "returned for a second trip" signal;
//	                             max-min >= 7 days implies >= 2 lineages).
//	                             Grouping by lineage keeps re-finalizing one
//	                             chat — a version save, which also emits
//	                             trip_created — from counting as a second
//	                             trip. Trade-off: the trips join drops events
//	                             whose trip row was later deleted, a slight
//	                             undercount (vs. the per-event overcount it
//	                             replaces); acceptable until trip deletion is
//	                             a real flow.
func (q *Queries) UserEngagementCounts(ctx context.Context, createdAt time.Time) (UserEngagementCountsRow, error) {
	row := q.db.QueryRow(ctx, userEngagementCounts, createdAt)
	var i UserEngagementCountsRow
	err := row.Scan(&i.ActiveUsers, &i.SessionFrequencyReturning, &i.SecondTripRetention)
	return i, err
}
