// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePlanChatSession = `-- name: DeletePlanChatSession :execrows
DELETE FROM plan_chat_sessions
WHERE user_id = $1 AND chat_id = $2
`

type DeletePlanChatSessionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID string    `json:"chat_id"`
}

func (q *Queries) DeletePlanChatSession(ctx context.Context, arg DeletePlanChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanChatSession, arg.UserID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStalePlanChatSessions = `-- name: DeleteStalePlanChatSessions :exec
DELETE FROM plan_chat_sessions
WHERE updated_at < now() - interval '60 days'
`

// Opportunistic prune (called from the list handler): a conversation idle for
// two months is abandoned, not "in progress".
func (q *Queries) DeleteStalePlanChatSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStalePlanChatSessions)
	return err
}

const getPlanChatSessionByChatID = `-- name: GetPlanChatSessionByChatID :one
SELECT id, user_id, chat_id, title, preview, summary, messages, message_count, created_at, updated_at FROM plan_chat_sessions
WHERE user_id = $1 AND chat_id = $2
`

type GetPlanChatSessionByChatIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID string    `json:"chat_id"`
}

func (q *Queries) GetPlanChatSessionByChatID(ctx context.Context, arg GetPlanChatSessionByChatIDParams) (PlanChatSession, error) {
	row := q.db.QueryRow(ctx, getPlanChatSessionByChatID, arg.UserID, arg.ChatID)
	var i PlanChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatID,
		&i.Title,
		&i.Preview,
		&i.Summary,
		&i.Messages,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResumablePlanChatSessions = `-- name: ListResumablePlanChatSessions :many
SELECT id, chat_id, title, preview, message_count, created_at, updated_at
FROM plan_chat_sessions s
WHERE s.user_id = $1
  AND NOT EXISTS (
      SELECT 1 FROM trips t
      WHERE t.user_id = s.user_id AND t.chat_id = s.chat_id
  )
ORDER BY s.updated_at DESC
LIMIT 10
`

type ListResumablePlanChatSessionsRow struct {
	ID           uuid.UUID `json:"id"`
	ChatID       string    `json:"chat_id"`
	Title        string    `json:"title"`
	Preview      string    `json:"preview"`
	MessageCount int32     `json:"message_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Summary columns only (messages can be large). A chat that already produced
// a trip is represented by its trip card, so it is excluded here — this also
// hides abandoned refine chats, whose chat_id belongs to an existing trip.
func (q *Queries) ListResumablePlanChatSessions(ctx context.Context, userID uuid.UUID) ([]ListResumablePlanChatSessionsRow, error) {
	rows, err := q.db.Query(ctx, listResumablePlanChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResumablePlanChatSessionsRow
	for rows.Next() {
		var i ListResumablePlanChatSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Title,
			&i.Preview,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlanChatSession = `-- name: UpsertPlanChatSession :exec
INSERT INTO plan_chat_sessions (
    user_id, chat_id, title, preview, summary, messages, message_count
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, chat_id) DO UPDATE SET
    preview = EXCLUDED.preview,
    summary = EXCLUDED.summary,
    messages = EXCLUDED.messages,
    message_count = EXCLUDED.message_count,
    updated_at = now()
`

type UpsertPlanChatSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ChatID       string    `json:"chat_id"`
	Title        string    `json:"title"`
	Preview      string    `json:"preview"`
	Summary      string    `json:"summary"`
	Messages     []byte    `json:"messages"`
	MessageCount int32     `json:"message_count"`
}

// Whole-transcript upsert, twice per /plan turn (start + deferred end).
// title is set once from the opening message and never overwritten, so the
// entry keeps a stable identity in the continue list.
func (q *Queries) UpsertPlanChatSession(ctx context.Context, arg UpsertPlanChatSessionParams) error {
	_, err := q.db.Exec(ctx, upsertPlanChatSession,
		arg.UserID,
		arg.ChatID,
		arg.Title,
		arg.Preview,
		arg.Summary,
		arg.Messages,
		arg.MessageCount,
	)
	return err
}
