// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaborators.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTripCollaborator = `-- name: CreateTripCollaborator :one
INSERT INTO trip_collaborators (chat_id, owner_id, user_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, chat_id, user_id) WHERE revoked_at IS NULL
DO UPDATE SET role = CASE WHEN EXCLUDED.role = 'editor' THEN 'editor'
                          ELSE trip_collaborators.role END
RETURNING role
`

type CreateTripCollaboratorParams struct {
	ChatID  string    `json:"chat_id"`
	OwnerID uuid.UUID `json:"owner_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

// Idempotent join, upgrade-never-downgrade: redeeming an editor link (or
// invite) upgrades an existing viewer membership; redeeming a viewer link as
// an editor keeps editor. Returns the resulting role.
func (q *Queries) CreateTripCollaborator(ctx context.Context, arg CreateTripCollaboratorParams) (string, error) {
	row := q.db.QueryRow(ctx, createTripCollaborator,
		arg.ChatID,
		arg.OwnerID,
		arg.UserID,
		arg.Role,
	)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getEditableTripByID = `-- name: GetEditableTripByID :one
SELECT t.id, t.user_id, t.created_at, t.updated_at, t.title, t.start_date, t.end_date, t.status, t.chat_id, t.summary, t.updated_by, t.travel_mode FROM trips t
WHERE t.id = $1
  AND (t.user_id = $2 OR EXISTS (
        SELECT 1 FROM trip_collaborators c
        WHERE c.user_id = $2 AND c.role = 'editor' AND c.revoked_at IS NULL
          AND c.owner_id = t.user_id AND c.chat_id = t.chat_id))
`

type GetEditableTripByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// The trip row when the caller may edit it: owner, or active editor
// collaborator on the row's lineage. chat_id = NULL (legacy trips) never
// matches a collaborator row, which is correct — they were never joinable.
func (q *Queries) GetEditableTripByID(ctx context.Context, arg GetEditableTripByIDParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getEditableTripByID, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
	)
	return i, err
}

const getViewableTripByID = `-- name: GetViewableTripByID :one
SELECT t.id, t.user_id, t.created_at, t.updated_at, t.title, t.start_date, t.end_date, t.status, t.chat_id, t.summary, t.updated_by, t.travel_mode, CASE WHEN t.user_id = $2 THEN 'owner' ELSE c.role END::text AS access
FROM trips t
LEFT JOIN trip_collaborators c ON c.owner_id = t.user_id AND c.chat_id = t.chat_id
     AND c.user_id = $2 AND c.revoked_at IS NULL
WHERE t.id = $1 AND (t.user_id = $2 OR c.id IS NOT NULL)
`

type GetViewableTripByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetViewableTripByIDRow struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	Title      string      `json:"title"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	Status     string      `json:"status"`
	ChatID     *string     `json:"chat_id"`
	Summary    *string     `json:"summary"`
	UpdatedBy  pgtype.UUID `json:"updated_by"`
	TravelMode *string     `json:"travel_mode"`
	Access     string      `json:"access"`
}

// Read access: owner or ANY active collaborator (viewer follows included).
// Returns the effective access so callers don't need a second lookup. The
// partial unique index guarantees at most one active membership per person,
// so the LEFT JOIN can't fan out.
func (q *Queries) GetViewableTripByID(ctx context.Context, arg GetViewableTripByIDParams) (GetViewableTripByIDRow, error) {
	row := q.db.QueryRow(ctx, getViewableTripByID, arg.ID, arg.UserID)
	var i GetViewableTripByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Access,
	)
	return i, err
}

const listCollaboratorsByOwnerAndChat = `-- name: ListCollaboratorsByOwnerAndChat :many
SELECT c.user_id, c.created_at, c.role, u.email,
       COALESCE(u.display_name, '')::text AS display_name
FROM trip_collaborators c
JOIN users u ON u.id = c.user_id
WHERE c.owner_id = $1 AND c.chat_id = $2 AND c.revoked_at IS NULL
ORDER BY c.created_at ASC
`

type ListCollaboratorsByOwnerAndChatParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
}

type ListCollaboratorsByOwnerAndChatRow struct {
	UserID      uuid.UUID `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	Role        string    `json:"role"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListCollaboratorsByOwnerAndChat(ctx context.Context, arg ListCollaboratorsByOwnerAndChatParams) ([]ListCollaboratorsByOwnerAndChatRow, error) {
	rows, err := q.db.Query(ctx, listCollaboratorsByOwnerAndChat, arg.OwnerID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollaboratorsByOwnerAndChatRow
	for rows.Next() {
		var i ListCollaboratorsByOwnerAndChatRow
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.Role,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCollaboratedTripsForUser = `-- name: ListLatestCollaboratedTripsForUser :many
SELECT latest.id, latest.user_id, latest.created_at, latest.updated_at,
       latest.title, latest.start_date, latest.end_date, latest.status,
       latest.chat_id, latest.role, latest.version_count,
       COALESCE(c2.cities, ARRAY[]::text[])::text[] AS cities,
       COALESCE(u.display_name, '')::text AS owner_name
FROM (
  SELECT DISTINCT ON (t.chat_id)
         t.id, t.user_id, t.created_at, t.updated_at, t.title, t.start_date,
         t.end_date, t.status, t.chat_id, c.role,
         count(*) OVER (PARTITION BY t.chat_id) AS version_count
  FROM trips t
  JOIN trip_collaborators c ON c.owner_id = t.user_id AND c.chat_id = t.chat_id
  WHERE c.user_id = $1 AND c.revoked_at IS NULL
  ORDER BY t.chat_id, t.created_at DESC
) latest
JOIN users u ON u.id = latest.user_id
LEFT JOIN LATERAL (
  SELECT array_agg(hub.city ORDER BY hub.first_pos) AS cities
  FROM (
    SELECT COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) AS city,
           MIN(ii.position) AS first_pos
    FROM itinerary_items ii
    WHERE ii.trip_id = latest.id
      AND COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) IS NOT NULL
    GROUP BY COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, ''))
  ) hub
) c2 ON true
ORDER BY latest.created_at DESC
`

type ListLatestCollaboratedTripsForUserRow struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	Title        string      `json:"title"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	Status       string      `json:"status"`
	ChatID       *string     `json:"chat_id"`
	Role         string      `json:"role"`
	VersionCount int64       `json:"version_count"`
	Cities       []string    `json:"cities"`
	OwnerName    string      `json:"owner_name"`
}

// "Shared with you": one row per collaborated lineage (latest version), same
// shape as ListLatestTripsByOwner plus the owner's display name.
func (q *Queries) ListLatestCollaboratedTripsForUser(ctx context.Context, userID uuid.UUID) ([]ListLatestCollaboratedTripsForUserRow, error) {
	rows, err := q.db.Query(ctx, listLatestCollaboratedTripsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestCollaboratedTripsForUserRow
	for rows.Next() {
		var i ListLatestCollaboratedTripsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
			&i.Role,
			&i.VersionCount,
			&i.Cities,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTripCollaborator = `-- name: RevokeTripCollaborator :execrows
UPDATE trip_collaborators SET revoked_at = now()
WHERE owner_id = $1 AND chat_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type RevokeTripCollaboratorParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeTripCollaborator(ctx context.Context, arg RevokeTripCollaboratorParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTripCollaborator, arg.OwnerID, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
