// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidEmailToken = `-- name: GetValidEmailToken :one
SELECT id, user_id, purpose, token_hash, expires_at, used_at, created_at FROM email_tokens
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
`

type GetValidEmailTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getValidEmailToken, arg.TokenHash, arg.Purpose)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEmailTokens = `-- name: InvalidateEmailTokens :exec
UPDATE email_tokens SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateEmailTokensParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

// Voids a user's outstanding tokens for a purpose (issuing a new reset link
// kills the previous one).
func (q *Queries) InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateEmailTokens, arg.UserID, arg.Purpose)
	return err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}
