// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTripInvite = `-- name: AcceptTripInvite :execrows
UPDATE trip_invites SET accepted_at = now(), accepted_by = $2
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
  AND expires_at > now()
`

type AcceptTripInviteParams struct {
	ID         uuid.UUID   `json:"id"`
	AcceptedBy pgtype.UUID `json:"accepted_by"`
}

// Race-safe single use: the WHERE re-checks pending state, so of two
// concurrent accepts only one row-update wins.
func (q *Queries) AcceptTripInvite(ctx context.Context, arg AcceptTripInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptTripInvite, arg.ID, arg.AcceptedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingInvitesByOwnerAndChat = `-- name: CountPendingInvitesByOwnerAndChat :one
SELECT count(*) FROM trip_invites
WHERE owner_id = $1 AND chat_id = $2
  AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

type CountPendingInvitesByOwnerAndChatParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
}

func (q *Queries) CountPendingInvitesByOwnerAndChat(ctx context.Context, arg CountPendingInvitesByOwnerAndChatParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitesByOwnerAndChat, arg.OwnerID, arg.ChatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTripInvite = `-- name: CreateTripInvite :one
INSERT INTO trip_invites (chat_id, owner_id, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, chat_id, owner_id, email, role, token_hash, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type CreateTripInviteParams struct {
	ChatID    string    `json:"chat_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTripInvite(ctx context.Context, arg CreateTripInviteParams) (TripInvite, error) {
	row := q.db.QueryRow(ctx, createTripInvite,
		arg.ChatID,
		arg.OwnerID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TripInvite
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, chat_id, owner_id, email, role, token_hash, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM trip_invites WHERE token_hash = $1
`

// Any state — lets accept be idempotent for the user who already redeemed.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (TripInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i TripInvite
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidInviteByTokenHash = `-- name: GetValidInviteByTokenHash :one
SELECT id, chat_id, owner_id, email, role, token_hash, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM trip_invites
WHERE token_hash = $1 AND accepted_at IS NULL AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidInviteByTokenHash(ctx context.Context, tokenHash string) (TripInvite, error) {
	row := q.db.QueryRow(ctx, getValidInviteByTokenHash, tokenHash)
	var i TripInvite
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitesByOwnerAndChat = `-- name: ListPendingInvitesByOwnerAndChat :many
SELECT id, chat_id, owner_id, email, role, token_hash, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM trip_invites
WHERE owner_id = $1 AND chat_id = $2
  AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at ASC
`

type ListPendingInvitesByOwnerAndChatParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
}

func (q *Queries) ListPendingInvitesByOwnerAndChat(ctx context.Context, arg ListPendingInvitesByOwnerAndChatParams) ([]TripInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByOwnerAndChat, arg.OwnerID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripInvite
	for rows.Next() {
		var i TripInvite
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.OwnerID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePendingInviteByEmail = `-- name: RevokePendingInviteByEmail :execrows
UPDATE trip_invites SET revoked_at = now()
WHERE owner_id = $1 AND chat_id = $2 AND email = $3
  AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokePendingInviteByEmailParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
	Email   string    `json:"email"`
}

// Reissue path: void the previous invite to this address before minting a
// fresh token (mirror of issueEmailToken's invalidate-then-create).
func (q *Queries) RevokePendingInviteByEmail(ctx context.Context, arg RevokePendingInviteByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePendingInviteByEmail, arg.OwnerID, arg.ChatID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTripInviteByID = `-- name: RevokeTripInviteByID :execrows
UPDATE trip_invites SET revoked_at = now()
WHERE id = $1 AND owner_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeTripInviteByIDParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) RevokeTripInviteByID(ctx context.Context, arg RevokeTripInviteByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTripInviteByID, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
