// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecommendationsByCityStatus = `-- name: CountRecommendationsByCityStatus :many
SELECT city, status, count(*) AS n
FROM local_recommendations
GROUP BY city, status
ORDER BY city ASC, status ASC
`

type CountRecommendationsByCityStatusRow struct {
	City   string `json:"city"`
	Status string `json:"status"`
	N      int64  `json:"n"`
}

// Coverage: how many published/draft pins exist per city.
func (q *Queries) CountRecommendationsByCityStatus(ctx context.Context) ([]CountRecommendationsByCityStatusRow, error) {
	rows, err := q.db.Query(ctx, countRecommendationsByCityStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRecommendationsByCityStatusRow
	for rows.Next() {
		var i CountRecommendationsByCityStatusRow
		if err := rows.Scan(&i.City, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLocalGuide = `-- name: CreateLocalGuide :one

INSERT INTO local_guides (source_id, title, city, neighborhood, body, hero_image_url, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, source_id, title, city, neighborhood, body, hero_image_url, status, created_at, updated_at
`

type CreateLocalGuideParams struct {
	SourceID     uuid.UUID `json:"source_id"`
	Title        string    `json:"title"`
	City         string    `json:"city"`
	Neighborhood *string   `json:"neighborhood"`
	Body         string    `json:"body"`
	HeroImageUrl *string   `json:"hero_image_url"`
	Status       string    `json:"status"`
}

// Guides --------------------------------------------------------------------
func (q *Queries) CreateLocalGuide(ctx context.Context, arg CreateLocalGuideParams) (LocalGuide, error) {
	row := q.db.QueryRow(ctx, createLocalGuide,
		arg.SourceID,
		arg.Title,
		arg.City,
		arg.Neighborhood,
		arg.Body,
		arg.HeroImageUrl,
		arg.Status,
	)
	var i LocalGuide
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.City,
		&i.Neighborhood,
		&i.Body,
		&i.HeroImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalRecommendation = `-- name: CreateLocalRecommendation :one

INSERT INTO local_recommendations
    (source_id, city, neighborhood, name, place_id, address, latitude, longitude,
     category, tip, quote, tags, status, place_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, source_id, city, neighborhood, name, place_id, address, latitude, longitude, category, tip, quote, tags, status, place_verified, created_at, updated_at
`

type CreateLocalRecommendationParams struct {
	SourceID      uuid.UUID `json:"source_id"`
	City          string    `json:"city"`
	Neighborhood  *string   `json:"neighborhood"`
	Name          string    `json:"name"`
	PlaceID       *string   `json:"place_id"`
	Address       *string   `json:"address"`
	Latitude      *float64  `json:"latitude"`
	Longitude     *float64  `json:"longitude"`
	Category      *string   `json:"category"`
	Tip           *string   `json:"tip"`
	Quote         *string   `json:"quote"`
	Tags          []string  `json:"tags"`
	Status        string    `json:"status"`
	PlaceVerified bool      `json:"place_verified"`
}

// Recommendations -----------------------------------------------------------
func (q *Queries) CreateLocalRecommendation(ctx context.Context, arg CreateLocalRecommendationParams) (LocalRecommendation, error) {
	row := q.db.QueryRow(ctx, createLocalRecommendation,
		arg.SourceID,
		arg.City,
		arg.Neighborhood,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.Tip,
		arg.Quote,
		arg.Tags,
		arg.Status,
		arg.PlaceVerified,
	)
	var i LocalRecommendation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.City,
		&i.Neighborhood,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Category,
		&i.Tip,
		&i.Quote,
		&i.Tags,
		&i.Status,
		&i.PlaceVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalSource = `-- name: CreateLocalSource :one

INSERT INTO local_sources (name, bio, photo_url, location, expertise, credibility, consent_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, bio, photo_url, location, expertise, credibility, consent_ref, created_at, updated_at
`

type CreateLocalSourceParams struct {
	Name        string  `json:"name"`
	Bio         *string `json:"bio"`
	PhotoUrl    *string `json:"photo_url"`
	Location    *string `json:"location"`
	Expertise   *string `json:"expertise"`
	Credibility *string `json:"credibility"`
	ConsentRef  *string `json:"consent_ref"`
}

// Local sources ------------------------------------------------------------
func (q *Queries) CreateLocalSource(ctx context.Context, arg CreateLocalSourceParams) (LocalSource, error) {
	row := q.db.QueryRow(ctx, createLocalSource,
		arg.Name,
		arg.Bio,
		arg.PhotoUrl,
		arg.Location,
		arg.Expertise,
		arg.Credibility,
		arg.ConsentRef,
	)
	var i LocalSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.PhotoUrl,
		&i.Location,
		&i.Expertise,
		&i.Credibility,
		&i.ConsentRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceMaterial = `-- name: CreateSourceMaterial :one

INSERT INTO local_source_material (source_id, kind, raw_text)
VALUES ($1, $2, $3)
RETURNING id, source_id, kind, raw_text, created_at
`

type CreateSourceMaterialParams struct {
	SourceID uuid.UUID `json:"source_id"`
	Kind     string    `json:"kind"`
	RawText  string    `json:"raw_text"`
}

// Source material (ingestion provenance) ------------------------------------
func (q *Queries) CreateSourceMaterial(ctx context.Context, arg CreateSourceMaterialParams) (LocalSourceMaterial, error) {
	row := q.db.QueryRow(ctx, createSourceMaterial, arg.SourceID, arg.Kind, arg.RawText)
	var i LocalSourceMaterial
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Kind,
		&i.RawText,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalGuide = `-- name: GetLocalGuide :one
SELECT g.id, g.source_id, g.title, g.city, g.neighborhood, g.body, g.hero_image_url, g.status, g.created_at, g.updated_at, s.name AS source_name, s.bio AS source_bio, s.photo_url AS source_photo_url,
       s.expertise AS source_expertise, s.credibility AS source_credibility
FROM local_guides g
JOIN local_sources s ON s.id = g.source_id
WHERE g.id = $1
`

type GetLocalGuideRow struct {
	ID                uuid.UUID `json:"id"`
	SourceID          uuid.UUID `json:"source_id"`
	Title             string    `json:"title"`
	City              string    `json:"city"`
	Neighborhood      *string   `json:"neighborhood"`
	Body              string    `json:"body"`
	HeroImageUrl      *string   `json:"hero_image_url"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SourceName        string    `json:"source_name"`
	SourceBio         *string   `json:"source_bio"`
	SourcePhotoUrl    *string   `json:"source_photo_url"`
	SourceExpertise   *string   `json:"source_expertise"`
	SourceCredibility *string   `json:"source_credibility"`
}

func (q *Queries) GetLocalGuide(ctx context.Context, id uuid.UUID) (GetLocalGuideRow, error) {
	row := q.db.QueryRow(ctx, getLocalGuide, id)
	var i GetLocalGuideRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.City,
		&i.Neighborhood,
		&i.Body,
		&i.HeroImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceName,
		&i.SourceBio,
		&i.SourcePhotoUrl,
		&i.SourceExpertise,
		&i.SourceCredibility,
	)
	return i, err
}

const getLocalRecommendation = `-- name: GetLocalRecommendation :one
SELECT id, source_id, city, neighborhood, name, place_id, address, latitude, longitude, category, tip, quote, tags, status, place_verified, created_at, updated_at FROM local_recommendations WHERE id = $1
`

func (q *Queries) GetLocalRecommendation(ctx context.Context, id uuid.UUID) (LocalRecommendation, error) {
	row := q.db.QueryRow(ctx, getLocalRecommendation, id)
	var i LocalRecommendation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.City,
		&i.Neighborhood,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Category,
		&i.Tip,
		&i.Quote,
		&i.Tags,
		&i.Status,
		&i.PlaceVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalSource = `-- name: GetLocalSource :one
SELECT id, name, bio, photo_url, location, expertise, credibility, consent_ref, created_at, updated_at FROM local_sources WHERE id = $1
`

func (q *Queries) GetLocalSource(ctx context.Context, id uuid.UUID) (LocalSource, error) {
	row := q.db.QueryRow(ctx, getLocalSource, id)
	var i LocalSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.PhotoUrl,
		&i.Location,
		&i.Expertise,
		&i.Credibility,
		&i.ConsentRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkGuideRecommendation = `-- name: LinkGuideRecommendation :exec
INSERT INTO local_guide_recommendations (guide_id, recommendation_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (guide_id, recommendation_id) DO UPDATE SET position = EXCLUDED.position
`

type LinkGuideRecommendationParams struct {
	GuideID          uuid.UUID `json:"guide_id"`
	RecommendationID uuid.UUID `json:"recommendation_id"`
	Position         int32     `json:"position"`
}

func (q *Queries) LinkGuideRecommendation(ctx context.Context, arg LinkGuideRecommendationParams) error {
	_, err := q.db.Exec(ctx, linkGuideRecommendation, arg.GuideID, arg.RecommendationID, arg.Position)
	return err
}

const listDraftGuides = `-- name: ListDraftGuides :many
SELECT g.id, g.source_id, g.title, g.city, g.neighborhood, g.body, g.hero_image_url, g.status, g.created_at, g.updated_at, s.name AS source_name FROM local_guides g
JOIN local_sources s ON s.id = g.source_id
WHERE g.status = 'draft'
ORDER BY g.created_at DESC
`

type ListDraftGuidesRow struct {
	ID           uuid.UUID `json:"id"`
	SourceID     uuid.UUID `json:"source_id"`
	Title        string    `json:"title"`
	City         string    `json:"city"`
	Neighborhood *string   `json:"neighborhood"`
	Body         string    `json:"body"`
	HeroImageUrl *string   `json:"hero_image_url"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	SourceName   string    `json:"source_name"`
}

func (q *Queries) ListDraftGuides(ctx context.Context) ([]ListDraftGuidesRow, error) {
	rows, err := q.db.Query(ctx, listDraftGuides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftGuidesRow
	for rows.Next() {
		var i ListDraftGuidesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.City,
			&i.Neighborhood,
			&i.Body,
			&i.HeroImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSources = `-- name: ListLocalSources :many
SELECT id, name, bio, photo_url, location, expertise, credibility, consent_ref, created_at, updated_at FROM local_sources ORDER BY name ASC
`

func (q *Queries) ListLocalSources(ctx context.Context) ([]LocalSource, error) {
	rows, err := q.db.Query(ctx, listLocalSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalSource
	for rows.Next() {
		var i LocalSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.PhotoUrl,
			&i.Location,
			&i.Expertise,
			&i.Credibility,
			&i.ConsentRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedGuidesByCity = `-- name: ListPublishedGuidesByCity :many
SELECT g.id, g.source_id, g.title, g.city, g.neighborhood, g.body, g.hero_image_url, g.status, g.created_at, g.updated_at, s.name AS source_name, s.photo_url AS source_photo_url
FROM local_guides g
JOIN local_sources s ON s.id = g.source_id
WHERE g.city ILIKE $1 AND g.status = 'published'
ORDER BY g.created_at DESC
`

type ListPublishedGuidesByCityRow struct {
	ID             uuid.UUID `json:"id"`
	SourceID       uuid.UUID `json:"source_id"`
	Title          string    `json:"title"`
	City           string    `json:"city"`
	Neighborhood   *string   `json:"neighborhood"`
	Body           string    `json:"body"`
	HeroImageUrl   *string   `json:"hero_image_url"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	SourceName     string    `json:"source_name"`
	SourcePhotoUrl *string   `json:"source_photo_url"`
}

func (q *Queries) ListPublishedGuidesByCity(ctx context.Context, city string) ([]ListPublishedGuidesByCityRow, error) {
	rows, err := q.db.Query(ctx, listPublishedGuidesByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedGuidesByCityRow
	for rows.Next() {
		var i ListPublishedGuidesByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.City,
			&i.Neighborhood,
			&i.Body,
			&i.HeroImageUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceName,
			&i.SourcePhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedRecommendationsByCity = `-- name: ListPublishedRecommendationsByCity :many
SELECT r.id, r.source_id, r.city, r.neighborhood, r.name, r.place_id, r.address, r.latitude, r.longitude, r.category, r.tip, r.quote, r.tags, r.status, r.place_verified, r.created_at, r.updated_at, s.name AS source_name, s.bio AS source_bio, s.photo_url AS source_photo_url,
       s.expertise AS source_expertise, s.credibility AS source_credibility
FROM local_recommendations r
JOIN local_sources s ON s.id = r.source_id
WHERE r.city ILIKE $1 AND r.status = 'published'
ORDER BY r.created_at DESC
`

type ListPublishedRecommendationsByCityRow struct {
	ID                uuid.UUID `json:"id"`
	SourceID          uuid.UUID `json:"source_id"`
	City              string    `json:"city"`
	Neighborhood      *string   `json:"neighborhood"`
	Name              string    `json:"name"`
	PlaceID           *string   `json:"place_id"`
	Address           *string   `json:"address"`
	Latitude          *float64  `json:"latitude"`
	Longitude         *float64  `json:"longitude"`
	Category          *string   `json:"category"`
	Tip               *string   `json:"tip"`
	Quote             *string   `json:"quote"`
	Tags              []string  `json:"tags"`
	Status            string    `json:"status"`
	PlaceVerified     bool      `json:"place_verified"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SourceName        string    `json:"source_name"`
	SourceBio         *string   `json:"source_bio"`
	SourcePhotoUrl    *string   `json:"source_photo_url"`
	SourceExpertise   *string   `json:"source_expertise"`
	SourceCredibility *string   `json:"source_credibility"`
}

// Hot read path (agent + browse). Attribution joined in.
func (q *Queries) ListPublishedRecommendationsByCity(ctx context.Context, city string) ([]ListPublishedRecommendationsByCityRow, error) {
	rows, err := q.db.Query(ctx, listPublishedRecommendationsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedRecommendationsByCityRow
	for rows.Next() {
		var i ListPublishedRecommendationsByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.City,
			&i.Neighborhood,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Category,
			&i.Tip,
			&i.Quote,
			&i.Tags,
			&i.Status,
			&i.PlaceVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceName,
			&i.SourceBio,
			&i.SourcePhotoUrl,
			&i.SourceExpertise,
			&i.SourceCredibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByGuide = `-- name: ListRecommendationsByGuide :many
SELECT r.id, r.source_id, r.city, r.neighborhood, r.name, r.place_id, r.address, r.latitude, r.longitude, r.category, r.tip, r.quote, r.tags, r.status, r.place_verified, r.created_at, r.updated_at, s.name AS source_name, s.photo_url AS source_photo_url,
       s.credibility AS source_credibility, gr.position AS guide_position
FROM local_guide_recommendations gr
JOIN local_recommendations r ON r.id = gr.recommendation_id
JOIN local_sources s ON s.id = r.source_id
WHERE gr.guide_id = $1 AND r.status = 'published'
ORDER BY gr.position ASC
`

type ListRecommendationsByGuideRow struct {
	ID                uuid.UUID `json:"id"`
	SourceID          uuid.UUID `json:"source_id"`
	City              string    `json:"city"`
	Neighborhood      *string   `json:"neighborhood"`
	Name              string    `json:"name"`
	PlaceID           *string   `json:"place_id"`
	Address           *string   `json:"address"`
	Latitude          *float64  `json:"latitude"`
	Longitude         *float64  `json:"longitude"`
	Category          *string   `json:"category"`
	Tip               *string   `json:"tip"`
	Quote             *string   `json:"quote"`
	Tags              []string  `json:"tags"`
	Status            string    `json:"status"`
	PlaceVerified     bool      `json:"place_verified"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SourceName        string    `json:"source_name"`
	SourcePhotoUrl    *string   `json:"source_photo_url"`
	SourceCredibility *string   `json:"source_credibility"`
	GuidePosition     int32     `json:"guide_position"`
}

// Published pins belonging to a guide, in narrative order, with attribution.
func (q *Queries) ListRecommendationsByGuide(ctx context.Context, guideID uuid.UUID) ([]ListRecommendationsByGuideRow, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByGuide, guideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendationsByGuideRow
	for rows.Next() {
		var i ListRecommendationsByGuideRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.City,
			&i.Neighborhood,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Category,
			&i.Tip,
			&i.Quote,
			&i.Tags,
			&i.Status,
			&i.PlaceVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceName,
			&i.SourcePhotoUrl,
			&i.SourceCredibility,
			&i.GuidePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByStatus = `-- name: ListRecommendationsByStatus :many
SELECT r.id, r.source_id, r.city, r.neighborhood, r.name, r.place_id, r.address, r.latitude, r.longitude, r.category, r.tip, r.quote, r.tags, r.status, r.place_verified, r.created_at, r.updated_at, s.name AS source_name, s.photo_url AS source_photo_url,
       s.credibility AS source_credibility
FROM local_recommendations r
JOIN local_sources s ON s.id = r.source_id
WHERE r.status = $1
ORDER BY r.created_at DESC
`

type ListRecommendationsByStatusRow struct {
	ID                uuid.UUID `json:"id"`
	SourceID          uuid.UUID `json:"source_id"`
	City              string    `json:"city"`
	Neighborhood      *string   `json:"neighborhood"`
	Name              string    `json:"name"`
	PlaceID           *string   `json:"place_id"`
	Address           *string   `json:"address"`
	Latitude          *float64  `json:"latitude"`
	Longitude         *float64  `json:"longitude"`
	Category          *string   `json:"category"`
	Tip               *string   `json:"tip"`
	Quote             *string   `json:"quote"`
	Tags              []string  `json:"tags"`
	Status            string    `json:"status"`
	PlaceVerified     bool      `json:"place_verified"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	SourceName        string    `json:"source_name"`
	SourcePhotoUrl    *string   `json:"source_photo_url"`
	SourceCredibility *string   `json:"source_credibility"`
}

// Admin curation queue, newest first, with the local's attribution fields.
func (q *Queries) ListRecommendationsByStatus(ctx context.Context, status string) ([]ListRecommendationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendationsByStatusRow
	for rows.Next() {
		var i ListRecommendationsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.City,
			&i.Neighborhood,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Category,
			&i.Tip,
			&i.Quote,
			&i.Tags,
			&i.Status,
			&i.PlaceVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceName,
			&i.SourcePhotoUrl,
			&i.SourceCredibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLocalGuideStatus = `-- name: SetLocalGuideStatus :one
UPDATE local_guides SET status = $2 WHERE id = $1 RETURNING id, source_id, title, city, neighborhood, body, hero_image_url, status, created_at, updated_at
`

type SetLocalGuideStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetLocalGuideStatus(ctx context.Context, arg SetLocalGuideStatusParams) (LocalGuide, error) {
	row := q.db.QueryRow(ctx, setLocalGuideStatus, arg.ID, arg.Status)
	var i LocalGuide
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.City,
		&i.Neighborhood,
		&i.Body,
		&i.HeroImageUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLocalRecommendationStatus = `-- name: SetLocalRecommendationStatus :one
UPDATE local_recommendations SET status = $2 WHERE id = $1 RETURNING id, source_id, city, neighborhood, name, place_id, address, latitude, longitude, category, tip, quote, tags, status, place_verified, created_at, updated_at
`

type SetLocalRecommendationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetLocalRecommendationStatus(ctx context.Context, arg SetLocalRecommendationStatusParams) (LocalRecommendation, error) {
	row := q.db.QueryRow(ctx, setLocalRecommendationStatus, arg.ID, arg.Status)
	var i LocalRecommendation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.City,
		&i.Neighborhood,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Category,
		&i.Tip,
		&i.Quote,
		&i.Tags,
		&i.Status,
		&i.PlaceVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocalRecommendation = `-- name: UpdateLocalRecommendation :one
UPDATE local_recommendations
SET city           = COALESCE($1, city),
    neighborhood   = COALESCE($2, neighborhood),
    name           = COALESCE($3, name),
    place_id       = COALESCE($4, place_id),
    address        = COALESCE($5, address),
    latitude       = COALESCE($6, latitude),
    longitude      = COALESCE($7, longitude),
    category       = COALESCE($8, category),
    tip            = COALESCE($9, tip),
    quote          = COALESCE($10, quote),
    place_verified = COALESCE($11, place_verified)
WHERE id = $12
RETURNING id, source_id, city, neighborhood, name, place_id, address, latitude, longitude, category, tip, quote, tags, status, place_verified, created_at, updated_at
`

type UpdateLocalRecommendationParams struct {
	City          *string   `json:"city"`
	Neighborhood  *string   `json:"neighborhood"`
	Name          *string   `json:"name"`
	PlaceID       *string   `json:"place_id"`
	Address       *string   `json:"address"`
	Latitude      *float64  `json:"latitude"`
	Longitude     *float64  `json:"longitude"`
	Category      *string   `json:"category"`
	Tip           *string   `json:"tip"`
	Quote         *string   `json:"quote"`
	PlaceVerified *bool     `json:"place_verified"`
	ID            uuid.UUID `json:"id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trips.sql UpdateTrip).
func (q *Queries) UpdateLocalRecommendation(ctx context.Context, arg UpdateLocalRecommendationParams) (LocalRecommendation, error) {
	row := q.db.QueryRow(ctx, updateLocalRecommendation,
		arg.City,
		arg.Neighborhood,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.Tip,
		arg.Quote,
		arg.PlaceVerified,
		arg.ID,
	)
	var i LocalRecommendation
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.City,
		&i.Neighborhood,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Category,
		&i.Tip,
		&i.Quote,
		&i.Tags,
		&i.Status,
		&i.PlaceVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
