// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, type, payload, trip_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, payload, trip_id, read_at, created_at
`

type InsertNotificationParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Type    string      `json:"type"`
	Payload []byte      `json:"payload"`
	TripID  pgtype.UUID `json:"trip_id"`
}

// Type-agnostic write: the caller supplies the discriminator and a payload bag
// carrying everything the client needs to render this row without a join.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Payload,
		arg.TripID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.TripID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, payload, trip_id, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListNotificationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// The whole feed for one user, newest first. No join — every row is
// self-describing via payload, so any notification type reads the same way.
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.TripID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

// Mark-all is the read model: opening the notification center clears the badge
// wholesale. No per-notification variant yet.
func (q *Queries) MarkNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
