// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_alerts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePriceAlertsByUser = `-- name: CountActivePriceAlertsByUser :one
SELECT count(*) FROM price_alerts
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActivePriceAlertsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePriceAlertsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceAlert = `-- name: CreatePriceAlert :one
INSERT INTO price_alerts (
    user_id, trip_id, origin, destination, depart_date, return_date,
    cabin_class, adults, target_price, currency, last_checked_price,
    last_checked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, trip_id, origin, destination, depart_date, return_date, cabin_class, adults, target_price, currency, last_checked_price, last_checked_at, last_notified_price, last_notified_at, status, created_at, updated_at
`

type CreatePriceAlertParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	TripID           pgtype.UUID        `json:"trip_id"`
	Origin           string             `json:"origin"`
	Destination      string             `json:"destination"`
	DepartDate       pgtype.Date        `json:"depart_date"`
	ReturnDate       pgtype.Date        `json:"return_date"`
	CabinClass       string             `json:"cabin_class"`
	Adults           int32              `json:"adults"`
	TargetPrice      *float64           `json:"target_price"`
	Currency         *string            `json:"currency"`
	LastCheckedPrice *float64           `json:"last_checked_price"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
}

func (q *Queries) CreatePriceAlert(ctx context.Context, arg CreatePriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRow(ctx, createPriceAlert,
		arg.UserID,
		arg.TripID,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.ReturnDate,
		arg.CabinClass,
		arg.Adults,
		arg.TargetPrice,
		arg.Currency,
		arg.LastCheckedPrice,
		arg.LastCheckedAt,
	)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ReturnDate,
		&i.CabinClass,
		&i.Adults,
		&i.TargetPrice,
		&i.Currency,
		&i.LastCheckedPrice,
		&i.LastCheckedAt,
		&i.LastNotifiedPrice,
		&i.LastNotifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePriceAlert = `-- name: DeletePriceAlert :execrows
DELETE FROM price_alerts
WHERE id = $1 AND user_id = $2
`

type DeletePriceAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePriceAlert(ctx context.Context, arg DeletePriceAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePriceAlert, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expirePastPriceAlerts = `-- name: ExpirePastPriceAlerts :execrows
UPDATE price_alerts
SET status = 'expired', updated_at = now()
WHERE status = 'active' AND depart_date < CURRENT_DATE
`

func (q *Queries) ExpirePastPriceAlerts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expirePastPriceAlerts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPriceAlertForUser = `-- name: GetPriceAlertForUser :one
SELECT id, user_id, trip_id, origin, destination, depart_date, return_date, cabin_class, adults, target_price, currency, last_checked_price, last_checked_at, last_notified_price, last_notified_at, status, created_at, updated_at FROM price_alerts
WHERE id = $1 AND user_id = $2
`

type GetPriceAlertForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPriceAlertForUser(ctx context.Context, arg GetPriceAlertForUserParams) (PriceAlert, error) {
	row := q.db.QueryRow(ctx, getPriceAlertForUser, arg.ID, arg.UserID)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ReturnDate,
		&i.CabinClass,
		&i.Adults,
		&i.TargetPrice,
		&i.Currency,
		&i.LastCheckedPrice,
		&i.LastCheckedAt,
		&i.LastNotifiedPrice,
		&i.LastNotifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDuePriceAlerts = `-- name: ListDuePriceAlerts :many
SELECT price_alerts.id, price_alerts.user_id, price_alerts.trip_id, price_alerts.origin, price_alerts.destination, price_alerts.depart_date, price_alerts.return_date, price_alerts.cabin_class, price_alerts.adults, price_alerts.target_price, price_alerts.currency, price_alerts.last_checked_price, price_alerts.last_checked_at, price_alerts.last_notified_price, price_alerts.last_notified_at, price_alerts.status, price_alerts.created_at, price_alerts.updated_at, users.email AS owner_email
FROM price_alerts
JOIN users ON users.id = price_alerts.user_id
WHERE price_alerts.status = 'active'
  AND price_alerts.depart_date >= CURRENT_DATE
  AND (price_alerts.last_checked_at IS NULL OR price_alerts.last_checked_at < $1)
ORDER BY price_alerts.last_checked_at ASC NULLS FIRST
LIMIT $2
`

type ListDuePriceAlertsParams struct {
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	Limit         int32              `json:"limit"`
}

type ListDuePriceAlertsRow struct {
	PriceAlert PriceAlert `json:"price_alert"`
	OwnerEmail string     `json:"owner_email"`
}

// Active alerts not yet checked in this cycle, oldest-checked first. The
// caller passes the freshness cutoff (now - check interval) and batch size.
func (q *Queries) ListDuePriceAlerts(ctx context.Context, arg ListDuePriceAlertsParams) ([]ListDuePriceAlertsRow, error) {
	rows, err := q.db.Query(ctx, listDuePriceAlerts, arg.LastCheckedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDuePriceAlertsRow
	for rows.Next() {
		var i ListDuePriceAlertsRow
		if err := rows.Scan(
			&i.PriceAlert.ID,
			&i.PriceAlert.UserID,
			&i.PriceAlert.TripID,
			&i.PriceAlert.Origin,
			&i.PriceAlert.Destination,
			&i.PriceAlert.DepartDate,
			&i.PriceAlert.ReturnDate,
			&i.PriceAlert.CabinClass,
			&i.PriceAlert.Adults,
			&i.PriceAlert.TargetPrice,
			&i.PriceAlert.Currency,
			&i.PriceAlert.LastCheckedPrice,
			&i.PriceAlert.LastCheckedAt,
			&i.PriceAlert.LastNotifiedPrice,
			&i.PriceAlert.LastNotifiedAt,
			&i.PriceAlert.Status,
			&i.PriceAlert.CreatedAt,
			&i.PriceAlert.UpdatedAt,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAlertsByUser = `-- name: ListPriceAlertsByUser :many
SELECT id, user_id, trip_id, origin, destination, depart_date, return_date, cabin_class, adults, target_price, currency, last_checked_price, last_checked_at, last_notified_price, last_notified_at, status, created_at, updated_at FROM price_alerts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPriceAlertsByUser(ctx context.Context, userID uuid.UUID) ([]PriceAlert, error) {
	rows, err := q.db.Query(ctx, listPriceAlertsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceAlert
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TripID,
			&i.Origin,
			&i.Destination,
			&i.DepartDate,
			&i.ReturnDate,
			&i.CabinClass,
			&i.Adults,
			&i.TargetPrice,
			&i.Currency,
			&i.LastCheckedPrice,
			&i.LastCheckedAt,
			&i.LastNotifiedPrice,
			&i.LastNotifiedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPriceAlertChecked = `-- name: MarkPriceAlertChecked :exec
UPDATE price_alerts
SET last_checked_price = $2,
    currency = COALESCE(currency, $3),
    last_checked_at = now(),
    updated_at = now()
WHERE id = $1
`

type MarkPriceAlertCheckedParams struct {
	ID               uuid.UUID `json:"id"`
	LastCheckedPrice *float64  `json:"last_checked_price"`
	Currency         *string   `json:"currency"`
}

func (q *Queries) MarkPriceAlertChecked(ctx context.Context, arg MarkPriceAlertCheckedParams) error {
	_, err := q.db.Exec(ctx, markPriceAlertChecked, arg.ID, arg.LastCheckedPrice, arg.Currency)
	return err
}

const markPriceAlertNotified = `-- name: MarkPriceAlertNotified :exec
UPDATE price_alerts
SET last_notified_price = $2,
    last_notified_at = now(),
    updated_at = now()
WHERE id = $1
`

type MarkPriceAlertNotifiedParams struct {
	ID                uuid.UUID `json:"id"`
	LastNotifiedPrice *float64  `json:"last_notified_price"`
}

func (q *Queries) MarkPriceAlertNotified(ctx context.Context, arg MarkPriceAlertNotifiedParams) error {
	_, err := q.db.Exec(ctx, markPriceAlertNotified, arg.ID, arg.LastNotifiedPrice)
	return err
}

const updatePriceAlert = `-- name: UpdatePriceAlert :one
UPDATE price_alerts
SET status = $3,
    target_price = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, trip_id, origin, destination, depart_date, return_date, cabin_class, adults, target_price, currency, last_checked_price, last_checked_at, last_notified_price, last_notified_at, status, created_at, updated_at
`

type UpdatePriceAlertParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	TargetPrice *float64  `json:"target_price"`
}

func (q *Queries) UpdatePriceAlert(ctx context.Context, arg UpdatePriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRow(ctx, updatePriceAlert,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.TargetPrice,
	)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TripID,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ReturnDate,
		&i.CabinClass,
		&i.Adults,
		&i.TargetPrice,
		&i.Currency,
		&i.LastCheckedPrice,
		&i.LastCheckedAt,
		&i.LastNotifiedPrice,
		&i.LastNotifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
