// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reengagement.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listTripsForReminder = `-- name: ListTripsForReminder :many
SELECT t.id,
       t.user_id,
       t.title,
       t.start_date,
       COALESCE(t.chat_id, t.id::text)::text AS lineage_key,
       u.email,
       u.display_name,
       u.reminders_opt_out
FROM trips t
JOIN users u ON u.id = t.user_id
WHERE t.status = 'planned'
  AND t.start_date = $1
  -- Latest planned+dated version of this lineage: no newer qualifying version
  -- exists (the flat equivalent of ListLatestTripsByOwner's DISTINCT ON, so one
  -- lineage yields at most one reminder row).
  AND NOT EXISTS (
    SELECT 1 FROM trips t2
    WHERE COALESCE(t2.chat_id, t2.id::text) = COALESCE(t.chat_id, t.id::text)
      AND t2.status = 'planned' AND t2.start_date IS NOT NULL
      AND t2.created_at > t.created_at
  )
  AND NOT EXISTS (
    SELECT 1 FROM reminder_sends rs
    WHERE rs.user_id = t.user_id
      AND rs.trip_lineage_key = COALESCE(t.chat_id, t.id::text)
      AND rs.kind = $2
  )
ORDER BY t.start_date
LIMIT $3
`

type ListTripsForReminderParams struct {
	TargetDate pgtype.Date `json:"target_date"`
	Kind       string      `json:"kind"`
	RowLimit   int32       `json:"row_limit"`
}

type ListTripsForReminderRow struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Title           string      `json:"title"`
	StartDate       pgtype.Date `json:"start_date"`
	LineageKey      string      `json:"lineage_key"`
	Email           string      `json:"email"`
	DisplayName     *string     `json:"display_name"`
	RemindersOptOut bool        `json:"reminders_opt_out"`
}

// Latest trip per lineage that is planned and departs on the target date
// (today+3 for 'trip_soon', today for 'trip_today'), joined to its owner. The
// DISTINCT ON collapses a trip's version chain to its newest planned version so
// one lineage reminds once. reminders_opt_out is RETURNED, not filtered: the
// caller still writes the in-app notification for opted-out users and only the
// email is skipped. Rows already recorded in reminder_sends for this (user,
// lineage, kind) are excluded so a kind fires once across ticks.
func (q *Queries) ListTripsForReminder(ctx context.Context, arg ListTripsForReminderParams) ([]ListTripsForReminderRow, error) {
	rows, err := q.db.Query(ctx, listTripsForReminder, arg.TargetDate, arg.Kind, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsForReminderRow
	for rows.Next() {
		var i ListTripsForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.StartDate,
			&i.LineageKey,
			&i.Email,
			&i.DisplayName,
			&i.RemindersOptOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForWeeklyNudge = `-- name: ListUsersForWeeklyNudge :many
SELECT u.id,
       u.email,
       u.display_name,
       u.nudges_opt_out
FROM users u
WHERE (u.last_weekly_nudge_at IS NULL OR u.last_weekly_nudge_at < $1)
  AND (
    EXISTS (SELECT 1 FROM trips t WHERE t.user_id = u.id AND t.status = 'draft')
    OR EXISTS (
      SELECT 1 FROM plan_chat_sessions s
      WHERE s.user_id = u.id
        AND NOT EXISTS (SELECT 1 FROM trips t2 WHERE t2.chat_id = s.chat_id)
    )
  )
  AND GREATEST(
        COALESCE((SELECT max(updated_at) FROM trips t3 WHERE t3.user_id = u.id), 'epoch'::timestamptz),
        COALESCE((SELECT max(updated_at) FROM plan_chat_sessions s2 WHERE s2.user_id = u.id), 'epoch'::timestamptz)
      ) < $1
ORDER BY u.id
LIMIT $2
`

type ListUsersForWeeklyNudgeParams struct {
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	RowLimit int32              `json:"row_limit"`
}

type ListUsersForWeeklyNudgeRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  *string   `json:"display_name"`
	NudgesOptOut bool      `json:"nudges_opt_out"`
}

// Users who started planning but went quiet: their most recent activity (max
// updated_at across trips and un-graduated plan chats) is older than the idle
// cutoff, they still have unfinished work (a draft trip OR a resumable plan
// chat — one whose chat_id has not become a trip), and they haven't been nudged
// within the window. nudges_opt_out is RETURNED, not filtered: the caller writes
// the in-app nudge for everyone and only the email is skipped. The cutoff is
// now()-7d supplied by the caller; it gates both the idle test and the
// once-a-week guard.
func (q *Queries) ListUsersForWeeklyNudge(ctx context.Context, arg ListUsersForWeeklyNudgeParams) ([]ListUsersForWeeklyNudgeRow, error) {
	rows, err := q.db.Query(ctx, listUsersForWeeklyNudge, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForWeeklyNudgeRow
	for rows.Next() {
		var i ListUsersForWeeklyNudgeRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.NudgesOptOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReminderSent = `-- name: RecordReminderSent :exec
INSERT INTO reminder_sends (user_id, trip_lineage_key, kind)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, trip_lineage_key, kind) DO NOTHING
`

type RecordReminderSentParams struct {
	UserID         uuid.UUID `json:"user_id"`
	TripLineageKey string    `json:"trip_lineage_key"`
	Kind           string    `json:"kind"`
}

// Dedup guard for the trip-reminder checker. Written BEFORE the email so a
// crashed/retried tick can never double-send (mirrors MarkPriceAlertNotified).
// ON CONFLICT is belt-and-suspenders — ListTripsForReminder already excludes
// recorded rows, but two overlapping ticks must not error on the unique index.
func (q *Queries) RecordReminderSent(ctx context.Context, arg RecordReminderSentParams) error {
	_, err := q.db.Exec(ctx, recordReminderSent, arg.UserID, arg.TripLineageKey, arg.Kind)
	return err
}

const touchWeeklyNudge = `-- name: TouchWeeklyNudge :exec
UPDATE users SET last_weekly_nudge_at = now() WHERE id = $1
`

// Records that we just nudged this user; the timestamp is the once-a-week guard
// ListUsersForWeeklyNudge checks. Written BEFORE the email so a crashed tick
// can't re-nudge.
func (q *Queries) TouchWeeklyNudge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchWeeklyNudge, id)
	return err
}
