// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createTripShare = `-- name: CreateTripShare :one
INSERT INTO trip_shares (chat_id, owner_id, token, role)
VALUES ($1, $2, $3, $4)
RETURNING id, chat_id, owner_id, token, role, created_at, revoked_at
`

type CreateTripShareParams struct {
	ChatID  string    `json:"chat_id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Token   string    `json:"token"`
	Role    string    `json:"role"`
}

func (q *Queries) CreateTripShare(ctx context.Context, arg CreateTripShareParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, createTripShare,
		arg.ChatID,
		arg.OwnerID,
		arg.Token,
		arg.Role,
	)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Token,
		&i.Role,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveShareByOwnerAndChat = `-- name: GetActiveShareByOwnerAndChat :one
SELECT id, chat_id, owner_id, token, role, created_at, revoked_at FROM trip_shares
WHERE owner_id = $1 AND chat_id = $2 AND role = $3 AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveShareByOwnerAndChatParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
	Role    string    `json:"role"`
}

// The owner's current (unrevoked) link of a given role for a chat lineage —
// share creation is idempotent per (lineage, role), so viewer and editor
// links coexist.
func (q *Queries) GetActiveShareByOwnerAndChat(ctx context.Context, arg GetActiveShareByOwnerAndChatParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, getActiveShareByOwnerAndChat, arg.OwnerID, arg.ChatID, arg.Role)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Token,
		&i.Role,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveShareByToken = `-- name: GetActiveShareByToken :one
SELECT id, chat_id, owner_id, token, role, created_at, revoked_at FROM trip_shares WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveShareByToken(ctx context.Context, token string) (TripShare, error) {
	row := q.db.QueryRow(ctx, getActiveShareByToken, token)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.OwnerID,
		&i.Token,
		&i.Role,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getLatestTripByOwnerAndChat = `-- name: GetLatestTripByOwnerAndChat :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary, updated_by FROM trips
WHERE user_id = $1 AND chat_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestTripByOwnerAndChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

// The newest version row in a chat lineage — what a share link resolves to.
func (q *Queries) GetLatestTripByOwnerAndChat(ctx context.Context, arg GetLatestTripByOwnerAndChatParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getLatestTripByOwnerAndChat, arg.UserID, arg.ChatID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
	)
	return i, err
}

const revokeSharesByOwnerAndChat = `-- name: RevokeSharesByOwnerAndChat :execrows
UPDATE trip_shares SET revoked_at = now()
WHERE owner_id = $1 AND chat_id = $2 AND revoked_at IS NULL
`

type RevokeSharesByOwnerAndChatParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
}

func (q *Queries) RevokeSharesByOwnerAndChat(ctx context.Context, arg RevokeSharesByOwnerAndChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSharesByOwnerAndChat, arg.OwnerID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
