// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip_checklist_items.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countChecklistItemsByTrip = `-- name: CountChecklistItemsByTrip :one
SELECT count(*) FROM trip_checklist_items WHERE trip_id = $1
`

func (q *Queries) CountChecklistItemsByTrip(ctx context.Context, tripID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChecklistItemsByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO trip_checklist_items (trip_id, category, title, position, auto)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trip_id, category, title, checked, position, auto, created_at, updated_at
`

type CreateChecklistItemParams struct {
	TripID   uuid.UUID `json:"trip_id"`
	Category string    `json:"category"`
	Title    string    `json:"title"`
	Position int32     `json:"position"`
	Auto     bool      `json:"auto"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (TripChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem,
		arg.TripID,
		arg.Category,
		arg.Title,
		arg.Position,
		arg.Auto,
	)
	var i TripChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Category,
		&i.Title,
		&i.Checked,
		&i.Position,
		&i.Auto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :execrows
DELETE FROM trip_checklist_items WHERE id = $1 AND trip_id = $2
`

type DeleteChecklistItemParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteChecklistItem(ctx context.Context, arg DeleteChecklistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChecklistItem, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChecklistItemsByTrip = `-- name: ListChecklistItemsByTrip :many
SELECT id, trip_id, category, title, checked, position, auto, created_at, updated_at FROM trip_checklist_items
WHERE trip_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListChecklistItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]TripChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripChecklistItem
	for rows.Next() {
		var i TripChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Category,
			&i.Title,
			&i.Checked,
			&i.Position,
			&i.Auto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE trip_checklist_items
SET category = COALESCE($1, category),
    title    = COALESCE($2, title),
    checked  = COALESCE($3, checked),
    position = COALESCE($4, position)
WHERE id = $5 AND trip_id = $6
RETURNING id, trip_id, category, title, checked, position, auto, created_at, updated_at
`

type UpdateChecklistItemParams struct {
	Category *string   `json:"category"`
	Title    *string   `json:"title"`
	Checked  *bool     `json:"checked"`
	Position *int32    `json:"position"`
	ID       uuid.UUID `json:"id"`
	TripID   uuid.UUID `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/booking_todos.sql
// UpdateBookingTodo). No auto-gating: every row — including AI-seeded auto=true
// rows — is fully editable by the traveler; that is the whole point of not
// reusing booking_todos. COALESCE means fields can be overwritten but not
// cleared to NULL (these columns are all NOT NULL anyway).
func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (TripChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.Category,
		arg.Title,
		arg.Checked,
		arg.Position,
		arg.ID,
		arg.TripID,
	)
	var i TripChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Category,
		&i.Title,
		&i.Checked,
		&i.Position,
		&i.Auto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
