// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeItineraryItemPositionGap = `-- name: CloseItineraryItemPositionGap :exec
UPDATE itinerary_items SET position = position - 1
WHERE trip_id = $1 AND position > $2
`

type CloseItineraryItemPositionGapParams struct {
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

// Compacts positions after a delete (mirror of ShiftItineraryItemPositions).
func (q *Queries) CloseItineraryItemPositionGap(ctx context.Context, arg CloseItineraryItemPositionGapParams) error {
	_, err := q.db.Exec(ctx, closeItineraryItemPositionGap, arg.TripID, arg.Position)
	return err
}

const countActiveTripLineagesByOwner = `-- name: CountActiveTripLineagesByOwner :one
SELECT count(DISTINCT COALESCE(chat_id, id::text)) FROM trips WHERE user_id = $1
`

// Active trips for the free-cap signal (specs/free-cap-instrumentation):
// one per chat lineage, the same COALESCE(chat_id, id::text) grouping
// ListLatestTripsByOwner's DISTINCT ON uses — new versions of an existing
// lineage don't add to the count. All saved trips count as active (no
// archived status exists today).
func (q *Queries) CountActiveTripLineagesByOwner(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTripLineagesByOwner, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, position, name, place_id, address, latitude, longitude, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id
`

type CreateItineraryItemParams struct {
	TripID                uuid.UUID   `json:"trip_id"`
	Position              int32       `json:"position"`
	Name                  string      `json:"name"`
	PlaceID               *string     `json:"place_id"`
	Address               *string     `json:"address"`
	Latitude              float64     `json:"latitude"`
	Longitude             float64     `json:"longitude"`
	Category              *string     `json:"category"`
	TimeOfDay             *string     `json:"time_of_day"`
	City                  *string     `json:"city"`
	DayTripFrom           *string     `json:"day_trip_from"`
	Day                   *int32      `json:"day"`
	LocalSourceName       *string     `json:"local_source_name"`
	LocalRecommendationID pgtype.UUID `json:"local_recommendation_id"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.Position,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.TimeOfDay,
		arg.City,
		arg.DayTripFrom,
		arg.Day,
		arg.LocalSourceName,
		arg.LocalRecommendationID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Category,
		&i.TimeOfDay,
		&i.City,
		&i.DayTripFrom,
		&i.Day,
		&i.LocalSourceName,
		&i.LocalRecommendationID,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, status, chat_id, summary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary
`

type CreateTripParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Title   string    `json:"title"`
	Status  string    `json:"status"`
	ChatID  *string   `json:"chat_id"`
	Summary *string   `json:"summary"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Title,
		arg.Status,
		arg.ChatID,
		arg.Summary,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
	)
	return i, err
}

const deleteItineraryItem = `-- name: DeleteItineraryItem :execrows
DELETE FROM itinerary_items WHERE id = $1 AND trip_id = $2
`

type DeleteItineraryItemParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteItineraryItem(ctx context.Context, arg DeleteItineraryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItem, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItineraryItemsByTrip = `-- name: DeleteItineraryItemsByTrip :exec
DELETE FROM itinerary_items WHERE trip_id = $1
`

func (q *Queries) DeleteItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItineraryItemsByTrip, tripID)
	return err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips t
WHERE t.user_id = $1
  AND (
    t.id = $2
    OR t.chat_id = (
      SELECT chat_id FROM trips
      WHERE id = $2 AND user_id = $1 AND chat_id IS NOT NULL
    )
  )
`

type DeleteTripParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

// Deletes the trip and, when it belongs to a chat group, all its versions.
// Legacy trips (chat_id NULL) match only by id, so a single row is removed.
func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItineraryItemsByTrip = `-- name: GetItineraryItemsByTrip :many
SELECT id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id FROM itinerary_items WHERE trip_id = $1 ORDER BY position ASC
`

func (q *Queries) GetItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, getItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryItem
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Position,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.Category,
			&i.TimeOfDay,
			&i.City,
			&i.DayTripFrom,
			&i.Day,
			&i.LocalSourceName,
			&i.LocalRecommendationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripByIDAndOwner = `-- name: GetTripByIDAndOwner :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDAndOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByIDAndOwner(ctx context.Context, arg GetTripByIDAndOwnerParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByIDAndOwner, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
	)
	return i, err
}

const getTripForUpdate = `-- name: GetTripForUpdate :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary FROM trips WHERE id = $1 FOR UPDATE
`

// Row-locks the trip for the duration of the transaction. Full-itinerary
// rewrites (replaceTripSection) and reorders read-then-write the whole item
// set; without this lock two concurrent writers interleave under READ
// COMMITTED and both item sets survive the delete/reinsert.
func (q *Queries) GetTripForUpdate(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripForUpdate, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
	)
	return i, err
}

const listLatestTripsByOwner = `-- name: ListLatestTripsByOwner :many
SELECT latest.id, latest.user_id, latest.created_at, latest.updated_at,
       latest.title, latest.start_date, latest.end_date, latest.status,
       latest.chat_id, latest.version_count,
       COALESCE(c.cities, ARRAY[]::text[])::text[] AS cities
FROM (
  SELECT DISTINCT ON (COALESCE(chat_id, id::text))
         id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id,
         count(*) OVER (PARTITION BY COALESCE(chat_id, id::text)) AS version_count
  FROM trips WHERE user_id = $1
  ORDER BY COALESCE(chat_id, id::text), created_at DESC
) latest
LEFT JOIN LATERAL (
  SELECT array_agg(hub.city ORDER BY hub.first_pos) AS cities
  FROM (
    SELECT COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) AS city,
           MIN(ii.position) AS first_pos
    FROM itinerary_items ii
    WHERE ii.trip_id = latest.id
      AND COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) IS NOT NULL
    GROUP BY COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, ''))
  ) hub
) c ON true
ORDER BY latest.created_at DESC
`

type ListLatestTripsByOwnerRow struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	Title        string      `json:"title"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	Status       string      `json:"status"`
	ChatID       *string     `json:"chat_id"`
	VersionCount int64       `json:"version_count"`
	Cities       []string    `json:"cities"`
}

// One row per chat group (latest version), with how many versions exist and the
// trip's distinct hub cities (day_trip_from ?? city) in first-appearance order
// for a location summary. Legacy trips with NULL chat_id stand alone.
func (q *Queries) ListLatestTripsByOwner(ctx context.Context, userID uuid.UUID) ([]ListLatestTripsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLatestTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestTripsByOwnerRow
	for rows.Next() {
		var i ListLatestTripsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
			&i.VersionCount,
			&i.Cities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripVersionsByChat = `-- name: ListTripVersionsByChat :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary FROM trips WHERE user_id = $1 AND chat_id = $2 ORDER BY created_at DESC
`

type ListTripVersionsByChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

func (q *Queries) ListTripVersionsByChat(ctx context.Context, arg ListTripVersionsByChatParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripVersionsByChat, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByOwner = `-- name: ListTripsByOwner :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary FROM trips WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTripsByOwner(ctx context.Context, userID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ChatID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItineraryItemPosition = `-- name: SetItineraryItemPosition :exec
UPDATE itinerary_items SET position = $3 WHERE id = $1 AND trip_id = $2
`

type SetItineraryItemPositionParams struct {
	ID       uuid.UUID `json:"id"`
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetItineraryItemPosition(ctx context.Context, arg SetItineraryItemPositionParams) error {
	_, err := q.db.Exec(ctx, setItineraryItemPosition, arg.ID, arg.TripID, arg.Position)
	return err
}

const shiftItineraryItemPositions = `-- name: ShiftItineraryItemPositions :exec
UPDATE itinerary_items SET position = position + 1
WHERE trip_id = $1 AND position >= $2
`

type ShiftItineraryItemPositionsParams struct {
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

// Opens a gap at the given position for an insert; the (trip_id, position)
// index is non-unique, so the unordered update cannot collide.
func (q *Queries) ShiftItineraryItemPositions(ctx context.Context, arg ShiftItineraryItemPositionsParams) error {
	_, err := q.db.Exec(ctx, shiftItineraryItemPositions, arg.TripID, arg.Position)
	return err
}

const touchTrip = `-- name: TouchTrip :exec
UPDATE trips SET updated_at = now() WHERE id = $1
`

// Itinerary-item writes don't touch the trips row, so bump updated_at by hand.
func (q *Queries) TouchTrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTrip, id)
	return err
}

const tripLineageExists = `-- name: TripLineageExists :one
SELECT EXISTS(
  SELECT 1 FROM trips WHERE user_id = $1 AND chat_id = $2
) AS lineage_exists
`

type TripLineageExistsParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

// Whether the owner already has any trip in this chat lineage. persistTrip
// runs it inside the same transaction as its insert to distinguish a
// brand-new lineage from a new version of an existing one: the free-cap
// active_trips signal may only fire for new lineages (a version save never
// moves the lineage count and can never emit —
// specs/free-cap-instrumentation).
func (q *Queries) TripLineageExists(ctx context.Context, arg TripLineageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tripLineageExists, arg.UserID, arg.ChatID)
	var lineage_exists bool
	err := row.Scan(&lineage_exists)
	return lineage_exists, err
}

const updateItineraryItem = `-- name: UpdateItineraryItem :one
UPDATE itinerary_items
SET name        = COALESCE($1, name),
    place_id    = COALESCE($2, place_id),
    address     = COALESCE($3, address),
    latitude    = COALESCE($4, latitude),
    longitude   = COALESCE($5, longitude),
    category    = COALESCE($6, category),
    time_of_day = COALESCE($7, time_of_day),
    city        = COALESCE($8, city),
    day_trip_from = COALESCE($9, day_trip_from),
    day         = COALESCE($10, day)
WHERE id = $11 AND trip_id = $12
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id
`

type UpdateItineraryItemParams struct {
	Name        *string   `json:"name"`
	PlaceID     *string   `json:"place_id"`
	Address     *string   `json:"address"`
	Latitude    *float64  `json:"latitude"`
	Longitude   *float64  `json:"longitude"`
	Category    *string   `json:"category"`
	TimeOfDay   *string   `json:"time_of_day"`
	City        *string   `json:"city"`
	DayTripFrom *string   `json:"day_trip_from"`
	Day         *int32    `json:"day"`
	ID          uuid.UUID `json:"id"`
	TripID      uuid.UUID `json:"trip_id"`
}

// Partial update (COALESCE narg pattern, like UpdateTrip). Attribution columns
// (local_source_name, local_recommendation_id) are deliberately not updatable —
// they are snapshots written by the agent.
func (q *Queries) UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, updateItineraryItem,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.TimeOfDay,
		arg.City,
		arg.DayTripFrom,
		arg.Day,
		arg.ID,
		arg.TripID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Category,
		&i.TimeOfDay,
		&i.City,
		&i.DayTripFrom,
		&i.Day,
		&i.LocalSourceName,
		&i.LocalRecommendationID,
	)
	return i, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title      = COALESCE($1, title),
    start_date = COALESCE($2, start_date),
    end_date   = COALESCE($3, end_date),
    status     = COALESCE($4, status),
    chat_id    = COALESCE($5, chat_id)
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, status, chat_id, summary
`

type UpdateTripParams struct {
	Title     *string     `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Status    *string     `json:"status"`
	ChatID    *string     `json:"chat_id"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ChatID,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ChatID,
		&i.Summary,
	)
	return i, err
}
