// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, locale)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
	Locale       *string `json:"locale"`
}

// locale is the language negotiated on the signup request, so the very first
// email (verification) is already in the traveler's language rather than
// waiting for the client's first sync (specs/i18n-spanish).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, display_name
FROM users
WHERE is_admin = true
ORDER BY created_at ASC
`

type ListAdminUsersRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName *string   `json:"display_name"`
}

// All admin accounts (is_admin = true), for operational fan-out such as the
// ops-health degradation alert. Returns just what an alert needs: id + email +
// display name. Stable ordering by creation so the recipient list is
// deterministic.
func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now())
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const markUserOnboarded = `-- name: MarkUserOnboarded :one
UPDATE users SET onboarded_at = COALESCE(onboarded_at, now())
WHERE id = $1
RETURNING id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale
`

func (q *Queries) MarkUserOnboarded(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserOnboarded, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}

const setUserEmailOptOut = `-- name: SetUserEmailOptOut :one
UPDATE users SET
    reminders_opt_out = COALESCE($1, reminders_opt_out),
    nudges_opt_out    = COALESCE($2, nudges_opt_out)
WHERE id = $3
RETURNING id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale
`

type SetUserEmailOptOutParams struct {
	RemindersOptOut *bool     `json:"reminders_opt_out"`
	NudgesOptOut    *bool     `json:"nudges_opt_out"`
	ID              uuid.UUID `json:"id"`
}

// Category-partial opt-out setter: a NULL arg leaves that flag untouched, so a
// single query handles reminders-only, nudges-only, or all-at-once. Used by
// both the one-click unsubscribe link and the account-settings PATCH.
func (q *Queries) SetUserEmailOptOut(ctx context.Context, arg SetUserEmailOptOutParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserEmailOptOut, arg.RemindersOptOut, arg.NudgesOptOut, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = COALESCE($1, display_name),
    locale       = COALESCE($2, locale)
WHERE id = $3
RETURNING id, created_at, updated_at, email, password_hash, display_name, is_admin, onboarded_at, email_verified_at, reminders_opt_out, nudges_opt_out, last_weekly_nudge_at, locale
`

type UpdateUserProfileParams struct {
	DisplayName *string   `json:"display_name"`
	Locale      *string   `json:"locale"`
	ID          uuid.UUID `json:"id"`
}

// Partial account update: a NULL arg leaves that column untouched, so one query
// serves a display-name edit, a locale sync, or both. Same shape as
// SetUserEmailOptOut below. Locale is never cleared back to NULL — the client
// always resolves "System default" to a concrete language before syncing.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.Locale, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.OnboardedAt,
		&i.EmailVerifiedAt,
		&i.RemindersOptOut,
		&i.NudgesOptOut,
		&i.LastWeeklyNudgeAt,
		&i.Locale,
	)
	return i, err
}
